version: "3.6"
services:
  testnet-peer:
    image: proximax/proximax-sirius-chain:v0.6.9-buster
    ports:
      - 7902:7902
      - 7900:7900
      - 7901:7901
    volumes:
      - ./:/chainconfig
      - ./data:/data:rw
      - ./logs:/logs:rw
    restart: always
    entrypoint: /chainconfig/entrypoint.sh
