version: "3.6"
services:
  db:
    image: mongo:4.2-bionic
    command: bash -c "mongod --dbpath=/dbdata --bind_ip=db"
    stop_signal: SIGINT
    volumes:
    - ./mongodata:/dbdata:rw

  init-db:
    image: mongo:4.2-bionic
    command:  bash -c "/bin/bash /userconfig/mongors.sh"
    volumes:
    - ./mongodata:/dbdata:rw
    - ./scripts/mongo:/userconfig/:ro
    depends_on:
    - db

  catapult-api-node:
    # Downloads Catapult Server from specified Docker repo
    image: proximax/proximax-sirius-chain:v0.6.9-buster
    ports:
      - 7902:7902
      - 7900:7900
      - 7901:7901
    volumes:
      - ./:/chainconfig
      - ./data:/data:rw
      - ./logs:/logs:rw
    entrypoint: /bin/bash
    command: -c "rm -rf /data/server.lock && /sirius/bin/sirius.bc /chainconfig"

  rest-gateway:
    image: proximax/proximax-sirius-rest:v0.6.6
    ports:
    - "3000:3000"
    volumes:
    - ./restuserconfig/rest.json:/node_modules/catapult-api-rest/resources/rest.json
    command: ash -c "yarn start"
